# Configurações Gerais
data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"
  target_column: 'target'
  test_size: 0.2
  random_state: 42
  validation_size: 0.2

# Configurações de Preprocessamento
preprocessing:
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'

# Configurações dos Modelos
models:
  random_forest:
    enabled: true
    params:
      n_estimators: 200
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42

  xgboost:
    enabled: true
    params:
      n_estimators: 200
      max_depth: 6
      learning_rate: 0.1
      random_state: 42

  neural_network:
    enabled: true
    architecture:
      - {units: 64, activation: 'relu', dropout: 0.3}
      - {units: 32, activation: 'relu', dropout: 0.2}
      - {units: 16, activation: 'relu', dropout: 0.1}
    training:
      batch_size: 32
      epochs: 100
      early_stopping_patience: 10

# Configurações de Avaliação
evaluation:
  metrics:
    - 'accuracy'
    - 'precision'
    - 'recall'
    - 'f1'
    - 'roc_auc'
  cv_folds: 5